KEYWORD_QUERIES = [
    "pertussis",
    "rabies",
    "measles",
    "sarampión",
    "dengue",
    "meningitis",
    "malaria",
    "zika",
    "chikungunya",
    "mpox",
    "typhoid",
    "leptospirosis",
    "yersinia",
    "shigellosis"
]

SOURCE_IGNORE = [
    "Instapundit.com",
    "Mirror Online",
    "Theskepticsguide.org",
    "Biztoc.com",
    "RT",
    "Self",
    "PRNewswire",
    "Yahoo Entertainment",
    "Naturalnews.com",
    "New York Post",
    "Daily Mail",
    "Freerepublic.com",
    "Breitbart News",
    "The American Conservative",
    "Lewrockwell.com",
    "FREDZONE",
    "Fark.com",
    "Diamond.jp",
    "Slashdot.org",
    "buzzfeed",
    "Celebitchy.com",
]
