name: Scanner Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0,12 * * *'


env:
  NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scanner.py
      run: python scanner.py
      env:
        NEWSAPI_KEY: ${{ env.NEWSAPI_KEY }}

    - name: Commit articles.json and epinews.db
      run: |
        git config --global user.name 'Github scanner workflow'
        git config --global user.email 'workflow@example.com'
        git add -f data/articles.json epinews.db
        git commit -m 'Update articles.json and epinews.db'

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
